<a href="https://colab.research.google.com/github/dongiklee2/-/blob/main/20220316.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

github 자주 쓰이는 것들
	1) 변수 -  variables.ipynb, string 변수중에 중요한 것
	2) 문법(조건문 if 반복문 for) - syntax
	3) 함수 - function
	4) 패키지 - packages.ipynb / import

  변수는 크게 두가지, numbers와 string(문자) + list도 존재(대괄호를 쓰고 ,를 이용해 여러개를 넣으면 됨 / 뭐든 넣을 수 있음)
	-> a=1 b=2 등은 변수에 숫자를 넣은 것
	a = 1; print(type(a)) 에서 나오는 class int는 정수 type이라는 뜻
	float 소수, 이 때 1은 정수 int지만 1.0은 소수 float임, 즉 1과 1.0은 다르다
	string을 넣는 방법은 '' 안에 넣거나 " " 안에 넣으면 된다, ' 123'이면 타입은 str, 내용은 1 2 3 3개의 character를 가진 함수가 된다
	숫자를 적는다 하더라도 ' '가 되어 있으면 string이 되는 것

In [1]:
a = [1, 2, 3, 4]; print(type(a)); print(a[0])

<class 'list'>
1


list 중 일부분만 사용하는 것을 indexing이라고 한다
	파이썬은 위 함수의 경우 a[0]하면 1이 나옴 즉 0부터  시작, 만약 a[:]와 같이 입력하면 모든 내용이 다 나온다
	만약 2, 3만 가져오고 싶다면? a[1:3]라고 입력하면 된다, 즉 이는 a:b에서 a부터 b까지라는 뜻이 된다
		-> 왜 1:2가 아닌가? a[a:b]의 모양에서 뒷부분 b는 해당 항목을 포함하지 않음
		a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]로 바꾸고 만약 끝에서 하나 앞의 내용 즉 10을 하고 싶다면? a[2:-1]로 입력하면 나옴

In [2]:
a = [1,'a', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2]); print(a[2][1])

<class 'list'>
1
a
[3, '4']
4


1 'a' [3,'4']를 가지는 3 character 내용의 list임

a = [1,'a', [3, '4']] 에서 '4'만 내놓고 싶다면? a[2][1]로 하면 된다

a = 'abcdef123' 에서 일부분만 가지고 오고 싶다면? 
-> list와 string은 indexing 하는 방법이 똑같다!

dict에 관해
	a =	{"a": "apple", "b": "orange", "c": 2014} 이면 item 정보(내용)은 3개다
	list는 줄줄이 나열할 뿐 but dictionary는? 표제어와 함께 그것에 대한 설명이 있다 코딩 dict도 마찬가지!
	"a": "apple" 에서 "a"는 key, "apple"은 value가 된다
	dict를 쓸 때는 key 즉 제목값이 access를 하게 해 준다 so a[0]과 같이 list를 쓰는 것처럼 하면 안됨
	a["a"]라고 입력해야 apple이 나온다 이 때 key에는 숫자가 오든 문자가 오든 상관 X

String
len 함수? 내용의 길이를 말해줌
s = 'abcdef' 에서 길이는 6 so len(s) = 6

s[1]+s[3]+s[4:]*10 = ' bdefefefefefefefefefef '
string임에도 +를 사용할 수 있음

print(s[0]) 에서 print가 함수, 파이썬에서는 함수를 쓸 때 무조건 괄호()를 써야한다
		함수(입력) = 출력

  upper 함수? s.upper() = ABCDEF
	  대문자로 만들어 줌

s = ' this is a house built this year.\n' 만 실행하면 아무런 변화도 보이지 않는다 so print(s) 혹은 s라고 적어서 s가 변화했다는 사실을 볼 수 있게 해주자
  단, 셀에서 맨 마지막 줄에 있을 때만 print를 안써도 print 함수가 적용된다

result = s.find('house') 하면 11이 나온다
	  띄어 쓰기도 하나의 내용으로 생각한다 so 앞에서부터 0,1,2, 하면서 공백까지 합쳐가다보면 처음으로 house가 나오는 것이 11번째라는 뜻

s = s.strip() white space (지저분한 것들, 부적절한 띄어쓰기나 줄바꾸기 문장부호 등을 없애줌)

tokens = s.split(' ')	       빈칸을 포함하지 않되 빈칸을 중심으로 나눠서 list로 나누어 준다
		['this', 'is', 'a', 'house', 'built', 'this', 'year.']
	
s = ' '.join(tokens)	   빈칸을 이용해서 해당 list를 재조립하라
		' this is a house built this year. '

s = s.replace('this', 'that') this를 that으로 바꿔 줘라
		' that is a house built that year. '

Function
함수를 만드는 것은 쉽다!		def 함수명(입력변수) :(여기서 :콜론을 안적으면 오류남)
						return 출력변수

Syntax
  대표적인 것들 - 반복문 for while(지금 몰라도 됨), 조건문 if switch(지금 몰라도 됨)

  for의 경우


  for    in   :
		    (    )  (함수)					이러한 방식의 함수를 for-loop라고 함
	(이 부분 띄워야 함 안 띄우면 for와 밑의 함수가 독립적으로 시행)

  a = [1, 2, 3, 4]
	for i in range(len(a)):				여기서 range는? range(숫자) 를 하면 리스트가 만들어짐 ex) range(4)는 [0 1 2 3]
  	     print(a[i])

  a = ['red', 'green', 'blue', 'purple']
	for i in a:
   	      print(i)
		red
		green
		blue
		purple

  if의 경우


  a = 0			함수에서 =는 equal이 x, 오른쪽 내용을 왼쪽에 assign 해준다는 뜻
  if a == 0:			equal의 뜻은 == 만약 "아니라면"의 뜻을 주고 싶다면? !=를 대신 쓴다
	    print(a)

  a = 0
  if a == 0:
	    print(a)
  else:
	    print(a+1)		방식으로 사용해 a가 if에 맞지 않더라도 값을 낼 수 있음


  for i in range(1, 3):			range(1,3)? [1, 2]
	    for j in range(3, 5):		range(3,5)? [3, 4]
	        print(i*j)
			[3, 4, 6, 8]

  List Comprehension - list 안 쪽에 for 문이 들어가 있음
	a = [1, 2, 3, 4]
	b = [i for i in a if i >=2]		이건 for-loop해서 나오는 내용을 리스트로 만들라는 뜻
	b
		[2, 3, 4]

  a = ['red', 'green', 'blue', 'purple']
  b = [i for i in a if len(i) >=4]			red green blue purple을 i 자리에 넣고 len(i)가 4보다 크거나 같으면 for, so red는 len 값이 3이므로 if절 통과 불가
  b
		['green', 'blue', 'purple']

  Dict Comprehension - dict 안에 for 문이 들어가 있음
  a = ['red', 'green', 'blue', 'purple']
  b = [1, 2, 3, 4]
  c = {a[i]:b[i] for i in range(4)}			[0, 1, 2, 3]으로 두고 풀면? c는 {a[0]:b[0], a[1]:b[1], a[2]:b[2], a[3]:b[3]}
  c
  	{'blue': 3, 'green': 2, 'purple': 4, 'red': 1}

import - 여러 가지 패키지들(특정 사람들이 좋은 함수들을 만들어냄), 많이 쓰는 패키지들은 파이썬을 깔면 install이 되어 있어서 그냥 import만 하면 쓸 수 있음
	-> 설치는 되어 있어도 바로 쓸 수 있는 상태로 만들어 주어야 함
	import도 할 필요가 없는 것들 built in
	아무 것도 안 되어 있어서 install을 해야 하는 것

numpy의 역할? 난수를 만들거나 행렬을 만들거나 숫자를 가지고 간단한 통계처리 등
  
    numpy.random.randn(5) - numpy 안의 random 안의 randn function을 실행, 이 경우 5개의 랜덤 넘버가 만들어짐
	import numpy as np -> numpy를 간단히 하여 np로 사용할 수 있게 만듬
	n = np.random.randn(100) n이라는 variable에 100개의 난수 집어넣음

	matplotlib.pyplot.hist(n) 하면 n이라는 variable에 대한 표를 만들어 줌, hist란? histogram - 몇개의 칸으로 나누고 그 칸마다 해당하는 난수들이 몇 번 나오는가를 표로 제작
		ex)-2.5에서 -2 사이에는 해당하는 변수가 4개가 있다
	import matplotlib.pyplot - matplotlib.pyplot를 한 번에 import 해줌
	import matplotlib.pyplot as plt - 앞서 numpy의 경우와 같이 저 긴 package를 plt로 바꿔서 간단하게 사용할 수 있게 해줌

	from matplotlib import pyplot
	pyplot.hist(n)
							귀찮을 때 from을 이용해 빠르게 줄이는 방법들
	from matplotlib.pyplot import hist
	hist(n)

numpy와 matplotlib.ipynb(numpy_matplotlib.ipynb)
	%%%%%%%%%%%%%%%create nd arrays (≈matrices)
	Matrices란? Matrix(행렬, 직사각형의 숫자 array 배열)
	nd array? n-dimended array ex) 1d array 일차원 배열 등


	"ndarray"
	x = np.array([1,2,3])					[1 2 3]
	print(x)						<class 'numpy.ndarray'>	class란 특수한 변수를 말함, 즉 numpy에서 제공하는 특수한 변수 ndarray
	print(type(x))					(3,)			1d array라서 이렇게 나옴
	print(x.shape)			


	"arange"
	x = np.arange(0,10,2)
		여기서 괄호 안의 숫자는 increment 증가되는 것 즉 0과 10 사이에서 2만큼씩 늘어나는 숫자를 뽑아라 but 10은 포함 X				
	print(x)						
	print(type(x))					
	print(x.shape)					
	
	->

	[0 2 4 6 8]
	<class 'numpy.ndarray'>
	(5,)

	"linspace"
	x = np.linspace(0,10,6)		0에서 10까지중에 균등한 간격으로 6개의 숫자를 만들어라!
	print(x)
	print(type(x))
	print(x.shape)

	->

	[ 0.  2.  4.  6.  8. 10.]
	<class 'numpy.ndarray'>
	(6,)


	"list를 ndarray 하는 방법?"
	x = np.array([[1,2,3], [4,5,6]])
	print(x)
	print(type(x))
	print(x.shape)

	->

	[[1 2 3]
 	[4 5 6]]
	<class 'numpy.ndarray'>
	(2, 3)

	3d의 경우
	x = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
	print(x)
	print(type(x))
	print(x.shape)

	->

	[[[ 1  2  3]
 	 [ 4  5  6]]

	 [[ 7  8  9]
	  [10 11 12]]]
	<class 'numpy.ndarray'>
	(2, 2, 3)		3에 해당은 123, 두번째 2는 	123
						456
			첫번째 2는 전체를 의미
			123
			456

			789
			10 11 12

	"ones" 1로 채워진 array를 만듬, "zeros"도 마찬가지!
	x = np.ones([2, 2, 3])
	print(x)
	print(type(x))
	print(x.shape)

	->

	[[[1. 1. 1.]
	  [1. 1. 1.]]

	 [[1. 1. 1.]
	  [1. 1. 1.]]]
	<class 'numpy.ndarray'>
	(2, 2, 3)

	%%%%%%%%%%%%%%%%%%%%%%%%%create random numbers
	np.random.normal(0, 1, [2,3,4])		0과 1 사이에서 [2,3,4] 형태의 array를 만들어라!
	
	->

	array([[[-0.7684465 ,  2.02152979,  0.67345919,  1.42597255],
	        [ 0.10535416,  0.20301356,  1.04757358, -1.74130648],
	        [ 1.25230091, -1.16243132,  0.71093607,  1.01844288]],
	
	       [[-0.47182462,  0.38816534,  1.38832171,  0.11857628],
	        [-0.17241228,  0.67694336, -0.71748975,  1.45367011],
	        [-0.6923177 , -0.25912487,  0.58073832, -0.4477943 ]]])

	x = np.random.normal(0, 1, 100)		100개의 1d짜리 array들을 만든다 0에서 1사이 값으로
	print(x)
	plt.hist(x, bins=10)				bins? 가로축에 들어갈 칸의 개수를 정하는 것

	%%%%%%%%%%%%%%%%%%generate a sine curve
	plt.figure()						틀을 잡아주는 함수	

	theta1 = np.linspace(0, 2*np.pi, 100)				2*np.pi는 우리가 아는 파이, 즉 2파이를 말함
	s1 = np.sin(theta1)						so 해당 function은 0부터 2파이까지 사이에서 100개의 linspace한 숫자들을 만들어라
	theta2 = np.linspace(0, 2*np.pi, 100) + np.pi/2			np.sin? sin 함수를 만들라는 것!
	s2 = np.sin(theta2)
								theta는 입력, s는 출력
	plt.subplot(2, 1, 1) # (행, 열, 만들어진 그림중에 몇 번째를 쓸지)	전체 그림이 2줄, 세로로는 1줄, 앞서 만들어진 그림  중 1번째 거에 그림을 그려라
	plt.plot(theta1, s1, '.')					subplot은 plot을 꾸며주는 것, 여기서 .은 .형태로 그림을 그리라는 뜻
	plt.subplot(2, 1, 2) # (rows, columns, panel number)
	plt.plot(theta2, s2, '.')

	요소들이 상관관계가 높을 때 즉 correlation이 높을 때 r 즉 요소들로 만든 그래프의 기울기가 1에 가까워진다

	np.corrcoef(s1,s2)

	->

	array([[1.00000000e+00, 2.41915449e-17],
	       [2.41915449e-17, 1.00000000e+00]])			여기서 첫번째와 네번째는 항상 1이 나오므로 버리고, 2 3은 같으므로 사실상 2나 3 하나만 보면 됨